captainVersion: 4
services:
    # academy
    $$cap_appname:
        image: academykit/academy:$$cap_app_version
        restart: always
        environment:
            ConnectionStrings__DefaultConnection: 'Server=srv-captain--$$cap_appname-db;Database=$$cap_appname;User=dev;Password=$$cap_db_pass;Convert Zero Datetime=True;Allow User Variables=True;'
            JWT__DurationInMinutes: $$cap_auth_expiry_duration
            ConnectionStrings__HangfireConnection: 'Server=srv-captain--$$cap_appname-db;Database=$$cap_appname;User=dev;Password=$$cap_db_pass;Convert Zero Datetime=True;Allow User Variables=True;'
            Hangfire__User: $$cap_system_admin_username
            Hangfire__Password: $$cap_system_admin_password
            AppUrls__App: http://$$cap_appname.$$cap_root_domain
        caproverExtra:
            containerHttpPort: '80'
    # Database
    $$cap_appname-db:
        image: mariadb:11.2.4
        volumes:
            - $$cap_appname-db:/var/lib/mysql/data
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_pass
            MYSQL_USER: $$cap_appname
            MYSQL_PASSWORD: $$cap_db_pass
            MYSQL_DATABASE: $$cap_appname
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: '$$cap_app_version'
          label: AcademyKit Version
          defaultValue: 'latest'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/academykit/academy/tags
          validRegex: "/^([^\\s^\\/])+$/"

        - id: $$cap_db_pass
          label: Database Password
          defaultValue: $$cap_gen_random_hex(16)

        - id: $$cap_auth_expiry_duration
          label: Authentication JWT token expiry duration in minutes
          defaultValue: 60

        - id: $$cap_system_admin_username
          label: System Admin username
          defaultValue: 'sysAdmin'
          description: This will be your default login username for system to access background jobs dasbhoard

        - id: $$cap_system_admin_password
          label: System Admin Password
          defaultValue: $$cap_gen_random_hex(16)
          description: This will be your default login password for system to access background jobs dasbhoard
        
    instructions:
        start: |-
            🔥 🔥 👋 🚀 AI-driven Lightweight fresh alternative Thinkific, Teachable, and Moodle. 
            AcademyKit helps you build your academy for your team or customer in the simplest way possible.

            More details: https://academykit.co
        end: |-
            AcademyKit has been successfully deployed!
    displayName: AcademyKit
    isOfficial: true
    description: A sleek alternative to Moodle LMS for your organization.
    documentation: See https://docs.academykit.co